services:
  # Ollama service with GPU support
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia

  # Kokoro TTS service (CPU version - more reliable)
  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.2
    container_name: kokoro-tts
    restart: unless-stopped
    ports:
      - "8880:8880"

  # Web interface for Ollama (Open WebUI)
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - XDG_RUNTIME_DIR=/run/user/1000
    depends_on:
      - ollama
      - kokoro-tts
    volumes:
      - ollama_webui_data:/app/backend/data
      - /dev/shm:/dev/shm
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      - /run/user/1000/pipewire-0:/run/user/1000/pipewire-0:rw
    devices:
      - /dev/snd:/dev/snd
    security_opt:
      - seccomp:unconfined

volumes:
  ollama_data:
    driver: local
  ollama_webui_data:
    driver: local
